### ISSUE TITLE
Array elements

### ISSUE THREAD

**Issue by bajki-ib** [Vanilla-IceCream/vuex-bound#16]
Hi, how to edit or push element to array?

I'm getting "Error: [vuex] do not mutate vuex store state outside mutation handlers."

Thanks

**Comment by Shyam-Chen** [comment]
Can't set dynamically.

**Comment by bajki-ib** [comment]
Is there any way to do this?

**Comment by Shyam-Chen** [comment]
In your case, it seems that v-model is not needed. From now on [Pinia](https://pinia.vuejs.org/) will be the recommended default option for state management on Vuex.
