### ISSUE TITLE
store fields are truncated on mapModel

### ISSUE THREAD

**Issue by arraintxo** [Vanilla-IceCream/vuex-bound#6]
It seems that after the last update (41st), mapModel with array syntax is broken:

```
computed: {
    ...mapModel('mynamespace', ['filterType', 'filterText'])
}
```
creates this elements on the store when updating data

```
mynamespace:
    rType: "mySelectedFilterType",
    rText: "mySelectedFilterText"
```

If we change the mapModel syntax to this, it keeps working:
```
computed: {
    ...mapModel('mynamespace', {
        'filterType': state => state.filterType, 
        'filterText': state => state.filterText
    })
}
```

seems to be related to this new code on your last commit:

```
        const originState = valify.substring(
          valify.indexOf('state.') + 6,
          valify.indexOf(';') === -1 ? undefined : valify.indexOf(';'),
        );
```

I'm not able to fix it as I don't really now why you made this change. Would help a little more descriptive commit messages :)

Thanks for your work. This feels like a really usefull library for vuex

**Comment by Shyam-Chen** [comment]
Which Vuex version to use?

**Comment by arraintxo** [comment]
I'm using vuex:3.5.1 with vuex-bound:1.3.0

namespaced is set and properly working with vuex's mapGetter, mapStatus and others.

**Comment by Shyam-Chen** [comment]
I'm not sure, but the test speciation [passed](https://travis-ci.org/github/Vanilla-IceCream/vuex-bound/jobs/761904019). Maybe you could provide a simple repository?

**Comment by arraintxo** [comment]
Hi I created a pull request as I found why this was failing.

Longer than 6 character name state attribute names where failing, shorter where completely truncated so the "label" attribute was not being used. Test worked because "foo" was used, I changed to "fooBarBaz" and test started failing.

**Comment by Shyam-Chen** [comment]
release: v1.3.1

**Comment by arraintxo** [comment]
Thx
